server:
  port: 8080
spring:
  application:
    name: local-grpc-client

grpc:
  client:
    grpc-server:
      address: 'localhost:80'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext